### ISSUE TITLE
API errors are not being thrown to the front end

### ISSUE THREAD

**Issue by guites** [guites/socket-tables#10]
Errors like the one below are not being correctly passed to the final user. Instead, the app hangs on loading state.

```
linha 340 {
  client_id: [
    'O cliente não possui e-mail cadastrado no Sortweb, ou o e-mail cadastrado é inválido.'
  ]
}
(node:967) UnhandledPromiseRejectionWarning: TypeError: body used already for: https://app.sortweb.me/api/tasks.json
    at Response.consumeBody (/Users/guilhermegarcia/Node/sockettables/socket-tables/node_modules/node-fetch/lib/index.js:343:30)
    at Response.json (/Users/guilhermegarcia/Node/sockettables/socket-tables/node_modules/node-fetch/lib/index.js:268:22)
    at /Users/guilhermegarcia/Node/sockettables/socket-tables/index.js:347:39
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(node:967) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 12)
```

**Comment by guites** [comment]
commit https://github.com/guites/socket-tables/commit/6df1e8812a1272fe8eb45268c75297578ee59750 fixes case when error status is 403

**Comment by guites** [comment]
commit https://github.com/guites/socket-tables/commit/6df1e8812a1272fe8eb45268c75297578ee59750 also fixes status 400 errors (ex. client has no email)
